#!/bin/sh
#
# mksandbox.sh -- prepare an ODE sandbox for the OSFMK tree.
#
# Creates what has no vendor route and nothing else:
#
#   obj/ and export/at386    symlinks out of the tree (see below)
#   rc_files/osc/Buildconf.local   generated, never committed
#   a .sandboxrc for the caller to install as ~/.sandboxrc
#
# It does NOT drive the build.  OSF ships build_world for that, and
# OSFMK_BUILD.README documents it:
#
#   cp <repo>/sandboxrc.template ~/.sandboxrc    # edit the base path
#   cd <repo>/osfmk/src
#   sh ../../build_world
#
# ODE itself is not here either.  OSFMK_BUILD.README puts it in
# /usr/src/ode-bin, a sibling of DR3, with an apology: "Extract it into
# /usr/src/ (Yes, this isn't the best place for it, but we'll fix that
# at some future date)."  Build it with docs/tools/bootstrap-ode.sh.
#
set -eu

: "${ODE4LINUX:?set ODE4LINUX to your ode4linux clone}"
: "${MK_BUILD:=${HOME}/.cache/osfmk}"

REPO=$(git rev-parse --show-toplevel 2>/dev/null) || REPO=$(pwd)
OSFMK="${REPO}/osfmk"

[ -d "${OSFMK}/src" ] || {
	echo "no osfmk/src under ${REPO} -- wrong directory?" >&2; exit 1; }

mkdir -p "${MK_BUILD}/obj/at386" "${MK_BUILD}/export/at386"

# --- 1. obj/ and export/at386 ------------------------------------------
#
# These two symlinks are the only things this script puts inside the
# vendor tree, and they are unavoidable.  Buildconf line 108 defines
#
#	object_base ${sandbox_base}/obj/${target_machine}
#
# as a path definition with no setenv and no replace -- not an
# environment hook.  build resolves ../obj/at386 relative to the sandbox
# before Buildconf.local is read.  Overriding object_base and
# export_base in Buildconf.local was tested and fails with
#
#	No such directory: ../obj/at386
#
# and a two-line log; the build never starts.  mksb(1)'s "-obj mode dir"
# is not an answer either: it controls how the obj area is POPULATED
# from a backing tree, by linking or copying, not where it lives.
#
# Note export/at386 and NOT export/ -- osfmk/export/powermac is 240
# vendor files.
ln -sfn "${MK_BUILD}/obj" "${OSFMK}/obj"
ln -sfn "${MK_BUILD}/export/at386" "${OSFMK}/export/at386"

# --- 2. Buildconf.local ------------------------------------------------
#
# ODE's designed override point.  lib/libode/builddata.c looks for it at
# <sandbox_base>/rc_files/<project>/Buildconf.local and parses it AFTER
# Buildconf, so `replace setenv` wins.  Its own history says
# "CR 843. Added Buildconf.local functionality" -- it exists for this.
#
# Generated rather than committed so that
# git diff <import>..HEAD -- osfmk/ shows only deliberate source changes.
cat > "${OSFMK}/rc_files/osc/Buildconf.local" <<EOF
#
# Generated by docs/tools/mksandbox.sh -- do not edit, do not commit.
# ODE parses this after Buildconf; see lib/libode/builddata.c.
#

#
# SOURCEDIR: Buildconf line 132 sets it to the empty string, which is
# correct only for a sandbox with a backing chain, where
# BACKED_SOURCEDIR supplies the path.  We have no backing chain, so
# MAKESRCDIRPATH is empty, and after ODE make relocates into the object
# directory it has no path back to the sources.  The symptom is
# misleading: "don't know how to make build_all", which reads as a
# missing target rather than a missing search path.
#
replace setenv SOURCEDIR \${source_base}

#
# MAKESYSPATH: Buildconf points it at src/makedefs, which holds
# osf.*.mk but not sys.mk -- that lives in ODE's own mk directory.  ODE
# make reads this as a colon-separated list; its own comment in
# bin/make/parse.c line 2255 says "more than one may be given as
# dir1:...:dirn".  So we extend the path rather than planting symlinks
# to sys.mk, osf.man.mk and osf.doc.mk inside the vendor tree.
#
replace setenv MAKESYSPATH \${source_base}/makedefs:${ODE4LINUX}/src/ode/mk

#
# CARGS: extended, not replaced.  Buildconf already sets it under
# exactly this condition --
#   on i386 on_os linux target i386 setenv CARGS -D__NO_UNDERSCORES__
# -- and __NO_UNDERSCORES__ selects ELF symbol naming in i386/asm.h, so
# it must not be lost.  CARGS is last in _CCFLAGS_NOINC_ (osf.std.mk
# line 331), so it wins on any conflict.
#
# -m32: Buildconf assumes host word size equals target, as it did in
# 1998.  Without it libcthreads stops at cthread_internals.h:442,
# "#error Need an IN_KERNEL definition for current target" -- the guard
# tests defined(__i386), which gcc predefines only under -m32.  The
# header is right: there is no i386 target without it.
#
# -std=gnu89: required for the code to have its intended meaning, not a
# dialect preference.  "extern __inline__" means "emit no out-of-line
# copy" in gnu89 and "emit one here" in C99.  Two independent files
# depend on the gnu89 reading: i386/cthreads.h defines cthread_sp
# inline while libcthreads/i386/thread.c defines it out of line
# (compile error under C99), and i386/proc_reg.h does the same for
# get_cr0 (link error).
#
# -fcommon: tentative definitions that pre-GCC-10 linkers merged.
# Without it: multiple definition of null_security_token across
# libsa_fs, of in_kernel across libcthreads, and of
# _mach_init_routine / _thread_init_routine between libsa_mach's crt0
# and libmach.
#
# -fno-stack-protector: distro gcc defaults to -fstack-protector-strong,
# which emits calls to __stack_chk_fail_local.  That lives in libssp and
# a freestanding kernel has no such library.
#
# -fno-pic: REQUIRED TO RUN, and nothing in the build complains without
# it.  Modern distro gcc defaults to -fPIE.  A kernel is loaded at a
# fixed address and has no dynamic linker, so every GOT-relative access
# is garbage.  Without this flag the kernel links with zero undefined
# symbols and then faults in Switch_context, recurses inside
# t_page_fault and resets: 15,377 page faults and 2 CPU resets before
# the first line of output.  With it: zero faults, zero resets, and the
# banner appears.
#
# OSF never asks for PIC, which is what makes this a restoration of
# their configuration rather than an addition to it.  osf.gcc.mk lines
# 165-180 leave _ELF_PIC_ empty unless shared libraries are being
# built, and Buildconf line 158 forces it empty on Linux regardless:
#
#	on_os linux replace setenv _ELF_PIC_ ""
#
# So there is no vendor hook to reach for: the PIC comes from a
# compiler default that postdates the vendor by two decades.  Measured
# after adding it: get_pc_thunk symbols 7 -> 0, objects referencing the
# GOT 177 of 206 -> 1, kernel 1,106,116 -> 1,021,472 bytes.
#
# -fno-strict-aliasing: insurance, and the distinction is deliberate.
# At -O2 gcc assumes accesses through different types do not alias.
# Measured here: kern/ipc_kobject.c generates different code with and
# without the flag, so the optimiser IS making aliasing assumptions in
# this tree.  That is not the same as the code violating them, which
# has not been demonstrated.  FreeBSD's sys/conf/kern.pre.mk appends
# this flag whenever COPTFLAGS holds -O[23s] and it is missing, and
# Linux has carried it in kernel CFLAGS since 2.4 -- both conclusions
# drawn from long experience with code of exactly this vintage.
#
# NOT added, because they were measured and produce nothing:
# -fcf-protection=none and -fno-stack-clash-protection.  gcc 13.3.0
# enables -fcf-protection=full and -fstack-clash-protection by default
# on this host, and the built kernel contains zero endbr32 instructions
# and zero stack probes.  Adding flags for problems that do not occur
# is speculative work.
#
# -Wno-error=overflow: MIG's generated servers set a polymorphic
# disposition to ((mach_msg_type_name_t) -1) in an 8-bit field, which
# truncates to 255.  Deliberate, and the files are regenerated so they
# cannot be edited.
#
# -Wno-endif-labels: 373 instances of "#endif SOMETHING" across the
# kernel, a K&R convention naming which #if is being closed.  No
# semantic effect; fixing 373 sites would be a large deviation for none.
#
# NOT added: a blanket -Wno-error.  Keeping -Werror on everything else
# is what surfaced eight genuine type confusions in this tree, each of
# which is now fixed rather than silenced.
#
replace setenv CARGS "-D__NO_UNDERSCORES__ -m32 -std=gnu89 -fcommon -fno-stack-protector -fno-pic -fno-strict-aliasing -Wno-error=overflow -Wno-endif-labels"

#
# NO_STRICT_ANSI: a hook osf.gcc.mk line 94 provides --
#   ANSI_CC?=\${BASE_CC} \${...NO_STRICT_ANSI:D:U-pedantic -Wpointer-arith}
# -- so setting it drops -pedantic and nothing else.  Needed because
# decl_mutex_data(,name) passes an empty macro argument, undefined in
# C90 and legal from C99, used throughout ipc_space.h, vm_object.h and
# vm_page.h.  Narrower than disabling -Werror.
#
replace setenv NO_STRICT_ANSI 1

#
# ANSI_CC, TRADITIONAL_CC, HOST_CC: consumed by osf.std.mk under
# .if defined() at lines 120, 125 and 130, and defaulted with ?= in
# osf.gcc.mk.  Needed for one rule: conf/AT386/template.mk line 241
# builds genassym with \${_CC_} and no CFLAGS, so CARGS never reaches it.
# osf.std.mk line 140 resolves _CC_ through CCTYPE (default ansi) to
# _ansi_CC_, which falls back to bare "cc" when ANSI_CC is unset -- no
# -m32, so genassym is built 64-bit and queue.h's (integer_t)elt
# truncates an 8-byte pointer.  genassym computes the struct offsets
# that become assym.S, so a 64-bit genassym bakes 8-byte offsets into a
# 32-bit kernel.
#
replace setenv ANSI_CC "gcc -m32 -fno-builtin"
replace setenv TRADITIONAL_CC "gcc -m32 -fno-builtin -traditional"
replace setenv HOST_CC "gcc -m32 -fno-builtin"

#
# LDOPTS: conf/AT386/template.mk line 279 is "LDFLAGS+=\${LDOPTS}", the
# last line of the file, using += precisely so the link can be extended
# without editing it.  ld on x86-64 defaults to elf_x86_64 and reports
# "skipping incompatible ... cannot find -lmach" for 32-bit archives --
# it found them and refused them.
#
replace setenv LDOPTS "-m elf_i386"

#
# AT386_LDFLAGS: bootstrap/Makefile line 37 assigns LDFLAGS with a plain
# = , which clobbers LDOPTS, but it references \${\${TARGET_MACHINE}_LDFLAGS}
# -- so the per-machine variable is the hook for that link.  The value
# differs because that link is driven by gcc, not ld: "-m elf_i386" is
# an ld option and gcc rejects it with "unrecognized command-line
# option '-m'".
#
replace setenv AT386_LDFLAGS "-m32"
EOF

# --- 3. a sandboxrc, from OSF's own template ---------------------------
sed -e "s#/usr/src/DR3#${REPO}#" "${REPO}/sandboxrc.template" > "${MK_BUILD}/sandboxrc"

cat <<EOF

sandbox ready.

  obj           ${MK_BUILD}/obj
  export        ${MK_BUILD}/export/at386
  Buildconf     ${OSFMK}/rc_files/osc/Buildconf.local
  sandboxrc     ${MK_BUILD}/sandboxrc

OSFMK_BUILD.README's own flow, which is what to use:

  cp ${MK_BUILD}/sandboxrc ~/.sandboxrc
  . ${REPO}/set_ode_path.sh
  export PATH="${MK_BUILD}/ode-sandbox/tools/at386_linux/bin:\$PATH"
  cd ${REPO}/osfmk/src
  sh ../../build_world

build_world is shipped mode 100644, hence "sh".  Its final makeboot
step is PowerMac-specific; AT386 has conf/AT386/config.makeboot and a
boot path under stand/AT386, so that step differs for us.
EOF
